# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define jobs to be invoked later in a workflow.
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: "mvn dependency:resolve"
      - run:
          name: Run tests
          command: "mvn test"
      - run:
          name: Generate coverage report
          command: "mvn jacoco:report"
      - store_artifacts:
          path: target/site/jacoco
          destination: coverage-report
      - store_test_results:
          path: target/surefire-reports

# Orchestrate jobs using workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - run-tests
