# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define jobs to be invoked later in a workflow.
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-tests:
    docker:
      - image: cimg/openjdk:17.0 # Use JDK 17 image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: "./mvnw dependency:resolve" # Resolve Maven dependencies
      - run:
          name: Run tests
          command: "./mvnw test" # Run tests using Maven
      - run:
          name: Generate coverage report
          command: "./mvnw jacoco:report" # Generate code coverage report using JaCoCo
      - store_artifacts:
          path: target/site/jacoco
          destination: coverage-report
      - store_test_results:
          path: target/surefire-reports # Directory containing test results

# Orchestrate jobs using workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - run-tests
