name: Java CI with Checkstyle and Javadoc

on:
  push:
    branches: [tp5]
  pull_request:
    branches: [tp5]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Étape 3 : Compiler le projet
      - name: Build with Maven
        run: mvn clean install

      # Étape 4 : Analyser le code avec Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      # Étape 5 : Générer Javadoc
      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      # Étape 6 : Publier les rapports Checkstyle et Javadoc comme artefacts
      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: target/site/checkstyle.html

      - name: Upload Javadoc
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: target/site/apidocs

      # Étape 7 : Vérifier le statut Checkstyle et créer un badge personnalisé
      - name: Check Checkstyle Result
        id: checkstyle
        run: |
          if grep -q '<error' target/checkstyle-result.xml; then
            echo "checkstyle_status=failed" >> $GITHUB_ENV
          else
            echo "checkstyle_status=passed" >> $GITHUB_ENV
          fi

      # Générer un badge en fonction du statut Checkstyle
      - name: Create Checkstyle Badge
        run: |
          if [ "${{ env.checkstyle_status }}" = "passed" ]; then
            curl -o checkstyle-badge.svg https://img.shields.io/badge/Checkstyle-Passed-brightgreen
          else
            curl -o checkstyle-badge.svg https://img.shields.io/badge/Checkstyle-Failed-red
          fi
        shell: bash

      # Publier le badge comme artefact
      - name: Upload Checkstyle Badge
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-badge
          path: checkstyle-badge.svg
